name: AsyncAPI documentation publishing

on:
  push:
    branches: [master]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v2

     
      #In case you do not want to use defaults, you, for example, want to use a different template
      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/github-action-for-generator@v0.2.0
        with:
          template: '@asyncapi/html-template@0.3.0' #In case of template from npm, because of @ it must be in quotes
          filepath: src/main/resources/api/asyncapi.yaml
          parameters: baseHref=/test-experiment/ sidebarOrganization=byTags #space separated list of key/values
          output: generated-kafka
          
      - name: List generated sources
        run: ls -la generated-kafka
    
