name: AsyncAPI documentation publishing

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v2

     
      #In case you do not want to use defaults, you, for example, want to use a different template
      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/github-action-for-cli@v3.1.1
        with:
          template: '@asyncapi/java-spring-template' #In case of template from npm, because of @ it must be in quotes
          filepath: src/main/resources/spec/asyncApi/kafka.yml
          parameters: -p baseHref=/test-experiment/ sidebarOrganization=byTags #space separated list of key/values
          output: generated-kafka
          
      - name: List generated sources
        run: ls -la generated-kafka
    
